import { Colors } from "../styles";

export default [
	{
		id: "1",
		categoryName: "Digital Marketing",
		desc: "30 courses",
		cta: "CourseDetails",
		categoryImage: require("../assets/img/categories/marketting.png"),
		bgColorPrimary: Colors.primary,
		bgColorSecondary: Colors.secondary,
	},
	{
		id: "2",
		categoryName: "Finance & Accounts",
		desc: "10 Courses",
		cta: "CourseDetails",
		categoryImage: require("../assets/img/categories/finance.png"),
		bgColorPrimary: Colors.info,
		bgColorSecondary: Colors.secondary,
	},
	{
		id: "3",
		categoryName: "Web Designing",
		desc: "10 Courses",
		cta: "CourseDetails",
		categoryImage: require("../assets/img/categories/webdesign.png"),
		bgColorPrimary: Colors.error,
		bgColorSecondary: Colors.warning,
	},
	{
		id: "4",
		categoryName: "UI & UX",
		desc: "10 Courses",
		cta: "CourseDetails",
		categoryImage: require("../assets/img/categories/uiux.png"),
		bgColorPrimary: Colors.secondary,
		bgColorSecondary: Colors.primary,
	},

	{
		id: "5",
		categoryName: "Business",
		desc: "30 Courses",
		cta: "CourseDetails",
		categoryImage: require("../assets/img/categories/business.png"),
		bgColorPrimary: Colors.info,
		bgColorSecondary: Colors.primary,
	},
	{
		id: "6",
		categoryName: "Photography",
		desc: "40 Courses",
		cta: "CourseDetails",
		categoryImage: require("../assets/img/categories/photography.png"),
		bgColorPrimary: Colors.secondary,
		bgColorSecondary: Colors.error,
	},
	{
		id: "7",
		categoryName: "Digital Marketing",
		desc: "30 courses",
		cta: "CourseDetails",
		categoryImage: require("../assets/img/categories/marketting.png"),
		bgColorPrimary: Colors.primary,
		bgColorSecondary: Colors.secondary,
	},
	{
		id: "8",
		categoryName: "Finance & Accounts",
		desc: "10 Courses",
		cta: "CourseDetails",
		categoryImage: require("../assets/img/categories/finance.png"),
		bgColorPrimary: Colors.info,
		bgColorSecondary: Colors.secondary,
	},
	{
		id: "9",
		categoryName: "Web Designing",
		desc: "10 Courses",
		cta: "CourseDetails",
		categoryImage: require("../assets/img/categories/webdesign.png"),
		bgColorPrimary: Colors.error,
		bgColorSecondary: Colors.warning,
	},
	{
		id: "10",
		categoryName: "UI & UX",
		desc: "10 Courses",
		cta: "CourseDetails",
		categoryImage: require("../assets/img/categories/uiux.png"),
		bgColorPrimary: Colors.secondary,
		bgColorSecondary: Colors.primary,
	},

	{
		id: "11",
		categoryName: "Business",
		desc: "30 Courses",
		cta: "CourseDetails",
		categoryImage: require("../assets/img/categories/business.png"),
		bgColorPrimary: Colors.info,
		bgColorSecondary: Colors.primary,
	},
	{
		id: "12",
		categoryName: "Photography",
		desc: "40 Courses",
		cta: "CourseDetails",
		categoryImage: require("../assets/img/categories/photography.png"),
		bgColorPrimary: Colors.secondary,
		bgColorSecondary: Colors.error,
	},
];
