export default [
	{
		id: "1",
		courseTitle: "The Web Developer Bootcamp 2.0",
		courseSubtitle: "Dr Anjela Yu ",
		cta: "CourseDetails",
		courseImage: require("../assets/img/courses/featured/developer-featured.jpeg"),
		ratings: "4.5",
		salePrice: 199,
		regularPrice: 299,
	},
	{
		id: "2",
		courseTitle: "Java Script The Complete Guide 2021",
		courseSubtitle: "Brad Travesy",
		cta: "CourseDetails",
		courseImage: require("../assets/img/courses/featured/javascript-featured.jpeg"),
		ratings: "4.5",
		salePrice: 499,
		regularPrice: 650,
	},
	{
		id: "3",
		courseTitle: "Machine Learning A-Z™: Hands-On Python & R In Data Science",
		courseSubtitle: "Kirill Eremeneko",
		cta: "CourseDetails",
		courseImage: require("../assets/img/courses/featured/python-2-featured.jpeg"),
		ratings: "5.0",
		salePrice: 99,
		regularPrice: 150,
	},
	{
		id: "4",
		courseTitle: "AWS Certified Solutions Architect - Associate 2020",
		courseSubtitle: "Mark Stain",
		cta: "CourseDetails",
		courseImage: require("../assets/img/courses/featured/aws-featured.png"),
		ratings: "4.5",
		salePrice: 499,
		regularPrice: 599,
	},
	{
		id: "5",
		courseTitle: "Photography Masterclass: A Complete Guide to Photography",
		courseSubtitle: "William Carnahan, Samuel",
		cta: "CourseDetails",
		courseImage: require("../assets/img/courses/featured/photography-featured.jpeg"),
		ratings: "4.5",
		salePrice: 499,
		regularPrice: 650,
	},
	{
		id: "6",
		courseTitle: "An Entire MBA in 1 Course:Award Winning Business School Prof",
		courseSubtitle: "Chirs Holla",
		cta: "CourseDetails",
		courseImage: require("../assets/img/courses/featured/mba-feature.jpeg"),
		ratings: "5",
		salePrice: 99,
		regularPrice: 150,
	},
	{
		id: "7",
		courseTitle: "2021 Complete Python Bootcamp From Zero to Hero in Python",
		courseSubtitle: "Joes portilla",
		cta: "CourseDetails",
		courseImage: require("../assets/img/courses/featured/python-featured.jpeg"),
		ratings: "5",
		salePrice: 99,
		regularPrice: 150,
	},
];
