import { Colors } from "../styles";

export default [
	{
		id: "1",
		lessonName: "HTML 5 & CSS Fundamentals",
		desc: "4 lecture 30 mins",
		cta: "CourseMoreDetails",
		image: require("../assets/img/courses/others/logo-html-5.png"),
		ctaBtnName: "Free",
	},
	{
		id: "2",
		lessonName: "HTML 5 Tags",
		desc: "9 lecture 30 mins",
		cta: "CourseMoreDetails",
		image: require("../assets/img/courses/others/logo-html-5.png"),
		ctaBtnName: "Pro",
	},
	{
		id: "3",
		lessonName: "HTML 5 - Website Structure",
		desc: "7 lecture 1 hr",
		cta: "CourseMoreDetails",
		image: require("../assets/img/courses/others/logo-html-5.png"),
		ctaBtnName: "Pro",
	},
	{
		id: "4",
		lessonName: "CSS 3 Fundamentals",
		desc: "7 lecture 1 hr",
		cta: "CourseMoreDetails",
		image: require("../assets/img/courses/others/CSS3.jpeg"),
		ctaBtnName: "Free",
	},
	{
		id: "5",
		lessonName: "Project - HTML 5 & CSS 3 Website",
		desc: "13 lecture 2 hr",
		cta: "CourseMoreDetails",
		image: require("../assets/img/courses/others/CSS3.jpeg"),
		ctaBtnName: "Pro",
	},
	{
		id: "6",
		lessonName: "Javascript Fundamentals",
		desc: "13 lecture 33 mins",
		cta: "CourseMoreDetails",
		image: require("../assets/img/courses/others/javascript.png"),
		ctaBtnName: "Pro",
	},
	{
		id: "7",
		lessonName: "Javascript Advances",
		desc: "10 lecture 55 mins",
		cta: "CourseMoreDetails",
		image: require("../assets/img/courses/others/javascript.png"),
		ctaBtnName: "Pro",
	},
	{
		id: "8",
		lessonName: "Bootstrap 5 Getting Started",
		lessonName: "Javascript Advances",
		desc: "10 lecture 55 mins",
		cta: "CourseMoreDetails",
		image: require("../assets/img/courses/others/javascript.png"),
		ctaBtnName: "Pro",
	},
	{
		id: "9",
		lessonName: "Bootstrap 5 Advanced",
		lessonName: "Javascript Advances",
		desc: "10 lecture 55 mins",
		cta: "CourseMoreDetails",
		image: require("../assets/img/courses/others/bootstrap.jpeg"),
		ctaBtnName: "Pro",
	},
	{
		id: "10",
		lessonName: "HTML 5 & CSS Fundamentals",
		desc: "4 lecture 30 mins",
		cta: "CourseMoreDetails",
		image: require("../assets/img/courses/others/logo-html-5.png"),
		ctaBtnName: "Free",
	},
	{
		id: "12",
		lessonName: "HTML 5 Tags",
		desc: "9 lecture 30 mins",
		cta: "CourseMoreDetails",
		image: require("../assets/img/courses/others/logo-html-5.png"),
		ctaBtnName: "Pro",
	},
	{
		id: "13",
		lessonName: "HTML 5 - Website Structure",
		desc: "7 lecture 1 hr",
		cta: "CourseMoreDetails",
		image: require("../assets/img/courses/others/logo-html-5.png"),
		ctaBtnName: "Pro",
	},
	{
		id: "14",
		lessonName: "CSS 3 Fundamentals",
		desc: "7 lecture 1 hr",
		cta: "CourseMoreDetails",
		image: require("../assets/img/courses/others/CSS3.jpeg"),
		ctaBtnName: "Free",
	},
	{
		id: "15",
		lessonName: "Project - HTML 5 & CSS 3 Website",
		desc: "13 lecture 2 hr",
		cta: "CourseMoreDetails",
		image: require("../assets/img/courses/others/CSS3.jpeg"),
		ctaBtnName: "Pro",
	},
	{
		id: "16",
		lessonName: "Javascript Fundamentals",
		desc: "13 lecture 33 mins",
		cta: "CourseMoreDetails",
		image: require("../assets/img/courses/others/javascript.png"),
		ctaBtnName: "Pro",
	},
	{
		id: "17",
		lessonName: "Javascript Advances",
		desc: "10 lecture 55 mins",
		cta: "CourseMoreDetails",
		image: require("../assets/img/courses/others/javascript.png"),
		ctaBtnName: "Pro",
	},
	{
		id: "18",
		lessonName: "Bootstrap 5 Getting Started",
		lessonName: "Javascript Advances",
		desc: "10 lecture 55 mins",
		cta: "CourseMoreDetails",
		image: require("../assets/img/courses/others/javascript.png"),
		ctaBtnName: "Pro",
	},
	{
		id: "19",
		lessonName: "Bootstrap 5 Advanced",
		lessonName: "Javascript Advances",
		desc: "10 lecture 55 mins",
		cta: "CourseMoreDetails",
		image: require("../assets/img/courses/others/bootstrap.jpeg"),
		ctaBtnName: "Pro",
	},
];
