export default [
	{
		id: "1",
		courseTitle: "Web Designing Advanced",
		courseSubtitle: "30 courses",
		cta: "Courses",
		courseImage: require("../assets/img/courses/webdesigning.jpg"),
		author: "James Jani",
	},
	{
		id: "2",
		courseTitle: "Python ProgramingPython Programing",
		courseSubtitle: "40 courses",
		cta: "Courses",
		courseImage: require("../assets/img/courses/python.jpeg"),
		author: "James Jani",
	},
	{
		id: "3",
		courseTitle: "Decision Making in Engineering Design",
		courseSubtitle: "40 courses",
		cta: "Courses",
		courseImage: require("../assets/img/courses/engineeringdesign.jpeg"),
		author: "James Jani",
	},
	{
		id: "4",
		courseTitle: "Photography",
		courseSubtitle: "10 courses",
		cta: "Courses",
		courseImage: require("../assets/img/courses/photography.jpg"),
		author: "James Jani",
	},
	{
		id: "5",
		courseTitle: "Data Science",
		courseSubtitle: "40 courses",
		cta: "Courses",
		courseImage: require("../assets/img/courses/data.jpeg"),
		author: "James Jani",
	},
	{
		id: "6",
		courseTitle: "Music",
		courseSubtitle: "40 courses",
		cta: "Courses",
		courseImage: require("../assets/img/courses/music.jpeg"),
		author: "James Jani",
	},
];
