export default [
	{
		id: "1",
		name: "John Martin",
		profilePic: require("../assets/img/profile/profile-1.jpeg"),
		review: "sdsd dsdsd re cxcdds ewd sas  ff dsd  ccdsd  dsdsc dsdsd dsd  dsd",
		rating: 4,
		date: "02-02-2020",
	},
	{
		id: "2",
		name: "Maxwell",
		profilePic: require("../assets/img/profile/profile-8.jpeg"),
		review: "ff dsd  ccdsd  dsdsc dsdsd dsd  dsd",
		rating: 3,
		date: "04-02-2020",
	},
	{
		id: "3",
		name: "Alex prem",
		profilePic: require("../assets/img/profile/profile-3.jpeg"),
		review:
			"sdsd dsdsd re cxcdds ewd sas  ff dsd  ccdsd  dsdsc dsdsd dsd  dsdsdsd dsdsd re cxcdds ewd sas  ff dsd  ccdsd  dsdsc dsdsd dsd  dsd",
		rating: 4,
		date: "03-02-2020",
	},
	{
		id: "4",
		name: "John Martin",
		profilePic: require("../assets/img/profile/profile-4.jpeg"),
		review: "sdsd dsdsd re cxcdds ewd sas  ff dsd  ccdsd  dsdsc dsdsd dsd  dsd",
		rating: 5,
		date: "02-02-2020",
	},
	{
		id: "4",
		name: "John Martin",
		profilePic: require("../assets/img/profile/profile-5.jpeg"),
		review: "sdsd dsdsd re cxcdds ewd sas  ff dsd  ccdsd  dsdsc dsdsd dsd  dsd",
		rating: 4,
		date: "02-02-2020",
	},
	{
		id: "5",
		name: "John Martin",
		profilePic: require("../assets/img/profile/profile-6.jpeg"),
		review: "sdsd dsdsd re cxcdds ewd sas  ff dsd  ccdsd  dsdsc dsdsd dsd  dsd",
		rating: 5,
		date: "02-02-2020",
	},
];
